language: node_js

node_js:
  - 8

before_install:
  - npm i -g npm@6

install:
  - npm ci

script: npm run test:coverage:ci

cache:
  directories:
    - $(npm config get prefix)/bin
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.npm
